/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#a6ecc3",
        "surface-dim": "#99e4b9",
        "on-primary-container": "#005f2b",
        "primary-fixed": "#64ff92",
        "tertiary": "#006574",
        "on-surface-variant": "#37654c",
        "secondary": "#565d5f",
        "surface-container-lowest": "#ffffff",
        "on-surface": "#023621",
        "outline": "#528166",
        "surface-container-low": "#c5fedb",
        "surface-container-highest": "#a6ecc3",
        "surface-container": "#b9f6d1",
        "error-dim": "#b92902",
        "on-error": "#ffefec",
        "on-primary": "#ceffd2",
        "error": "#b02500",
        "inverse-on-surface": "#77a78b",
        "surface": "#dcffe7",
        "secondary-container": "#dde4e6",
        "secondary-fixed": "#dde4e6",
        "surface-container-high": "#b0f1ca",
        "on-secondary-fixed": "#394043",
        "secondary-dim": "#4a5153",
        "on-secondary-container": "#4c5355",
        "on-secondary": "#edf4f6",
        "on-primary-fixed-variant": "#006a30",
        "background": "#dcffe7",
        "primary": "#006a30",
        "primary-dim": "#005d29",
        "tertiary-container": "#0ddfff",
        "on-error-container": "#520c00",
        "secondary-fixed-dim": "#cfd6d8",
        "error-container": "#f95630",
        "on-tertiary-fixed": "#00363f",
        "on-background": "#023621",
        "inverse-primary": "#64ff92",
        "surface-bright": "#dcffe7",
        "tertiary-fixed-dim": "#00d0ee",
        "primary-container": "#64ff92",
        "on-primary-fixed": "#004a20",
        "surface-tint": "#006a30",
        "tertiary-fixed": "#0ddfff",
        "on-secondary-fixed-variant": "#565d5f",
        "outline-variant": "#87b89b",
        "tertiary-dim": "#005866",
        "primary-fixed-dim": "#53f086",
        "inverse-surface": "#001208",
        "on-tertiary-fixed-variant": "#005562",
        "on-tertiary-container": "#004b57",
        "on-tertiary": "#dcf8ff"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans"],
        "body": ["Plus Jakarta Sans"],
        "label": ["Plus Jakarta Sans"]
      },
      borderRadius: {"DEFAULT": "1rem", "lg": "2rem", "xl": "3rem", "full": "9999px"},
    },
  },
  plugins: [],
}
